// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for CalendarConnectionProvider.
const (
	Google CalendarConnectionProvider = "google"
)

// Defines values for CalendarEventClassificationSource.
const (
	CalendarEventClassificationSourceFingerprint CalendarEventClassificationSource = "fingerprint"
	CalendarEventClassificationSourceLlm         CalendarEventClassificationSource = "llm"
	CalendarEventClassificationSourceManual      CalendarEventClassificationSource = "manual"
	CalendarEventClassificationSourceRule        CalendarEventClassificationSource = "rule"
)

// Defines values for CalendarEventClassificationStatus.
const (
	CalendarEventClassificationStatusClassified CalendarEventClassificationStatus = "classified"
	CalendarEventClassificationStatusPending    CalendarEventClassificationStatus = "pending"
	CalendarEventClassificationStatusSkipped    CalendarEventClassificationStatus = "skipped"
)

// Defines values for TimeEntrySource.
const (
	TimeEntrySourceCalendar TimeEntrySource = "calendar"
	TimeEntrySourceImport   TimeEntrySource = "import"
	TimeEntrySourceManual   TimeEntrySource = "manual"
)

// Defines values for ListCalendarEventsParamsClassificationStatus.
const (
	ListCalendarEventsParamsClassificationStatusClassified ListCalendarEventsParamsClassificationStatus = "classified"
	ListCalendarEventsParamsClassificationStatusPending    ListCalendarEventsParamsClassificationStatus = "pending"
	ListCalendarEventsParamsClassificationStatusSkipped    ListCalendarEventsParamsClassificationStatus = "skipped"
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Token string `json:"token"`
	User  User   `json:"user"`
}

// Calendar defines model for Calendar.
type Calendar struct {
	// Color Calendar color (hex code)
	Color        *string            `json:"color,omitempty"`
	ConnectionId openapi_types.UUID `json:"connection_id"`
	CreatedAt    time.Time          `json:"created_at"`

	// ExternalId Google Calendar ID (e.g., "primary", "user@example.com")
	ExternalId string             `json:"external_id"`
	Id         openapi_types.UUID `json:"id"`

	// IsPrimary Whether this is the user's primary calendar
	IsPrimary bool `json:"is_primary"`

	// IsSelected Whether this calendar is selected for syncing
	IsSelected   bool       `json:"is_selected"`
	LastSyncedAt *time.Time `json:"last_synced_at"`

	// Name Display name of the calendar
	Name      string     `json:"name"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// CalendarConnection defines model for CalendarConnection.
type CalendarConnection struct {
	CreatedAt    time.Time                  `json:"created_at"`
	Id           openapi_types.UUID         `json:"id"`
	LastSyncedAt *time.Time                 `json:"last_synced_at"`
	Provider     CalendarConnectionProvider `json:"provider"`
	UpdatedAt    *time.Time                 `json:"updated_at,omitempty"`
	UserId       openapi_types.UUID         `json:"user_id"`
}

// CalendarConnectionProvider defines model for CalendarConnection.Provider.
type CalendarConnectionProvider string

// CalendarEvent defines model for CalendarEvent.
type CalendarEvent struct {
	Attendees *[]string `json:"attendees,omitempty"`

	// CalendarColor Color of the source calendar (hex code)
	CalendarColor *string `json:"calendar_color"`

	// CalendarName Name of the source calendar
	CalendarName         *string                            `json:"calendar_name"`
	ClassificationSource *CalendarEventClassificationSource `json:"classification_source"`
	ClassificationStatus CalendarEventClassificationStatus  `json:"classification_status"`
	ConnectionId         openapi_types.UUID                 `json:"connection_id"`
	CreatedAt            time.Time                          `json:"created_at"`
	Description          *string                            `json:"description"`
	EndTime              time.Time                          `json:"end_time"`
	ExternalId           string                             `json:"external_id"`
	Id                   openapi_types.UUID                 `json:"id"`
	IsOrphaned           *bool                              `json:"is_orphaned,omitempty"`
	IsRecurring          *bool                              `json:"is_recurring,omitempty"`
	IsSuppressed         *bool                              `json:"is_suppressed,omitempty"`
	Project              *Project                           `json:"project,omitempty"`
	ProjectId            *openapi_types.UUID                `json:"project_id"`
	ResponseStatus       *string                            `json:"response_status"`
	StartTime            time.Time                          `json:"start_time"`
	Title                string                             `json:"title"`
	Transparency         *string                            `json:"transparency"`
	UpdatedAt            *time.Time                         `json:"updated_at,omitempty"`
	UserId               openapi_types.UUID                 `json:"user_id"`
}

// CalendarEventClassificationSource defines model for CalendarEvent.ClassificationSource.
type CalendarEventClassificationSource string

// CalendarEventClassificationStatus defines model for CalendarEvent.ClassificationStatus.
type CalendarEventClassificationStatus string

// ClassifyEventRequest defines model for ClassifyEventRequest.
type ClassifyEventRequest struct {
	// ProjectId Project to assign this event to. Omit or null to skip the event.
	ProjectId *openapi_types.UUID `json:"project_id,omitempty"`

	// Skip Set to true to mark as "did not attend" (skipped)
	Skip *bool `json:"skip,omitempty"`
}

// ClassifyEventResponse defines model for ClassifyEventResponse.
type ClassifyEventResponse struct {
	Event     CalendarEvent `json:"event"`
	TimeEntry *TimeEntry    `json:"time_entry,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// OAuthAuthorizeResponse defines model for OAuthAuthorizeResponse.
type OAuthAuthorizeResponse struct {
	// State State token for CSRF protection
	State string `json:"state"`

	// Url URL to redirect user for OAuth consent
	Url string `json:"url"`
}

// Project defines model for Project.
type Project struct {
	Color                  string             `json:"color"`
	CreatedAt              time.Time          `json:"created_at"`
	DoesNotAccumulateHours *bool              `json:"does_not_accumulate_hours,omitempty"`
	Id                     openapi_types.UUID `json:"id"`
	IsArchived             bool               `json:"is_archived"`
	IsBillable             bool               `json:"is_billable"`
	IsHiddenByDefault      *bool              `json:"is_hidden_by_default,omitempty"`
	Name                   string             `json:"name"`
	ShortCode              *string            `json:"short_code,omitempty"`
	UpdatedAt              *time.Time         `json:"updated_at,omitempty"`
	UserId                 openapi_types.UUID `json:"user_id"`
}

// ProjectCreate defines model for ProjectCreate.
type ProjectCreate struct {
	Color                  *string `json:"color,omitempty"`
	DoesNotAccumulateHours *bool   `json:"does_not_accumulate_hours,omitempty"`
	IsBillable             *bool   `json:"is_billable,omitempty"`
	IsHiddenByDefault      *bool   `json:"is_hidden_by_default,omitempty"`
	Name                   string  `json:"name"`
	ShortCode              *string `json:"short_code,omitempty"`
}

// ProjectUpdate defines model for ProjectUpdate.
type ProjectUpdate struct {
	Color                  *string `json:"color,omitempty"`
	DoesNotAccumulateHours *bool   `json:"does_not_accumulate_hours,omitempty"`
	IsArchived             *bool   `json:"is_archived,omitempty"`
	IsBillable             *bool   `json:"is_billable,omitempty"`
	IsHiddenByDefault      *bool   `json:"is_hidden_by_default,omitempty"`
	Name                   *string `json:"name,omitempty"`
	ShortCode              *string `json:"short_code,omitempty"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// SyncResult defines model for SyncResult.
type SyncResult struct {
	EventsCreated  int `json:"events_created"`
	EventsOrphaned int `json:"events_orphaned"`
	EventsUpdated  int `json:"events_updated"`
}

// TimeEntry defines model for TimeEntry.
type TimeEntry struct {
	CreatedAt time.Time `json:"created_at"`

	// Date The calendar day for this entry
	Date        openapi_types.Date `json:"date"`
	Description *string            `json:"description,omitempty"`

	// HasUserEdits Whether user has modified this entry
	HasUserEdits *bool              `json:"has_user_edits,omitempty"`
	Hours        float32            `json:"hours"`
	Id           openapi_types.UUID `json:"id"`

	// InvoiceId If invoiced, the invoice ID
	InvoiceId *openapi_types.UUID `json:"invoice_id"`
	Project   *Project            `json:"project,omitempty"`
	ProjectId openapi_types.UUID  `json:"project_id"`

	// Source How this entry was created
	Source    TimeEntrySource    `json:"source"`
	UpdatedAt *time.Time         `json:"updated_at,omitempty"`
	UserId    openapi_types.UUID `json:"user_id"`
}

// TimeEntrySource How this entry was created
type TimeEntrySource string

// TimeEntryCreate defines model for TimeEntryCreate.
type TimeEntryCreate struct {
	Date        openapi_types.Date `json:"date"`
	Description *string            `json:"description,omitempty"`
	Hours       float32            `json:"hours"`
	ProjectId   openapi_types.UUID `json:"project_id"`
}

// TimeEntryUpdate defines model for TimeEntryUpdate.
type TimeEntryUpdate struct {
	Description *string  `json:"description,omitempty"`
	Hours       *float32 `json:"hours,omitempty"`
}

// UpdateCalendarSourcesRequest defines model for UpdateCalendarSourcesRequest.
type UpdateCalendarSourcesRequest struct {
	// CalendarIds IDs of calendars to enable for syncing
	CalendarIds []openapi_types.UUID `json:"calendar_ids"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`
	Id        openapi_types.UUID  `json:"id"`
	Name      string              `json:"name"`
}

// GoogleCallbackParams defines parameters for GoogleCallback.
type GoogleCallbackParams struct {
	// Code Authorization code from Google
	Code string `form:"code" json:"code"`

	// State State parameter for CSRF protection
	State string `form:"state" json:"state"`
}

// ListCalendarEventsParams defines parameters for ListCalendarEvents.
type ListCalendarEventsParams struct {
	StartDate            *openapi_types.Date                           `form:"start_date,omitempty" json:"start_date,omitempty"`
	EndDate              *openapi_types.Date                           `form:"end_date,omitempty" json:"end_date,omitempty"`
	ClassificationStatus *ListCalendarEventsParamsClassificationStatus `form:"classification_status,omitempty" json:"classification_status,omitempty"`
	ConnectionId         *openapi_types.UUID                           `form:"connection_id,omitempty" json:"connection_id,omitempty"`
}

// ListCalendarEventsParamsClassificationStatus defines parameters for ListCalendarEvents.
type ListCalendarEventsParamsClassificationStatus string

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// IncludeArchived Include archived projects
	IncludeArchived *bool `form:"include_archived,omitempty" json:"include_archived,omitempty"`
}

// ListTimeEntriesParams defines parameters for ListTimeEntries.
type ListTimeEntriesParams struct {
	// StartDate Filter entries on or after this date
	StartDate *openapi_types.Date `form:"start_date,omitempty" json:"start_date,omitempty"`

	// EndDate Filter entries on or before this date
	EndDate *openapi_types.Date `form:"end_date,omitempty" json:"end_date,omitempty"`

	// ProjectId Filter by project
	ProjectId *openapi_types.UUID `form:"project_id,omitempty" json:"project_id,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody = SignupRequest

// ClassifyCalendarEventJSONRequestBody defines body for ClassifyCalendarEvent for application/json ContentType.
type ClassifyCalendarEventJSONRequestBody = ClassifyEventRequest

// UpdateCalendarSourcesJSONRequestBody defines body for UpdateCalendarSources for application/json ContentType.
type UpdateCalendarSourcesJSONRequestBody = UpdateCalendarSourcesRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = ProjectCreate

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = ProjectUpdate

// CreateTimeEntryJSONRequestBody defines body for CreateTimeEntry for application/json ContentType.
type CreateTimeEntryJSONRequestBody = TimeEntryCreate

// UpdateTimeEntryJSONRequestBody defines body for UpdateTimeEntry for application/json ContentType.
type UpdateTimeEntryJSONRequestBody = TimeEntryUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Google OAuth authorization URL
	// (GET /api/auth/google/authorize)
	GoogleAuthorize(w http.ResponseWriter, r *http.Request)
	// Handle Google OAuth callback
	// (GET /api/auth/google/callback)
	GoogleCallback(w http.ResponseWriter, r *http.Request, params GoogleCallbackParams)
	// Authenticate with email and password
	// (POST /api/auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// End the current session
	// (POST /api/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Get current authenticated user
	// (GET /api/auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// Create a new user account
	// (POST /api/auth/signup)
	Signup(w http.ResponseWriter, r *http.Request)
	// List calendar events with filters
	// (GET /api/calendar-events)
	ListCalendarEvents(w http.ResponseWriter, r *http.Request, params ListCalendarEventsParams)
	// Classify a calendar event (assign to project or skip)
	// (PUT /api/calendar-events/{id}/classify)
	ClassifyCalendarEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List user's calendar connections
	// (GET /api/calendars)
	ListCalendarConnections(w http.ResponseWriter, r *http.Request)
	// Disconnect a calendar
	// (DELETE /api/calendars/{id})
	DeleteCalendarConnection(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List available calendars for a connection
	// (GET /api/calendars/{id}/sources)
	ListCalendarSources(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update which calendars are selected for sync
	// (PUT /api/calendars/{id}/sources)
	UpdateCalendarSources(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Trigger sync for a calendar connection
	// (POST /api/calendars/{id}/sync)
	SyncCalendar(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List all projects
	// (GET /api/projects)
	ListProjects(w http.ResponseWriter, r *http.Request, params ListProjectsParams)
	// Create a new project
	// (POST /api/projects)
	CreateProject(w http.ResponseWriter, r *http.Request)
	// Delete a project
	// (DELETE /api/projects/{id})
	DeleteProject(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get a project by ID
	// (GET /api/projects/{id})
	GetProject(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update a project
	// (PUT /api/projects/{id})
	UpdateProject(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List time entries
	// (GET /api/time-entries)
	ListTimeEntries(w http.ResponseWriter, r *http.Request, params ListTimeEntriesParams)
	// Create a new time entry
	// (POST /api/time-entries)
	CreateTimeEntry(w http.ResponseWriter, r *http.Request)
	// Delete a time entry
	// (DELETE /api/time-entries/{id})
	DeleteTimeEntry(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get a time entry by ID
	// (GET /api/time-entries/{id})
	GetTimeEntry(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update a time entry
	// (PUT /api/time-entries/{id})
	UpdateTimeEntry(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get Google OAuth authorization URL
// (GET /api/auth/google/authorize)
func (_ Unimplemented) GoogleAuthorize(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Handle Google OAuth callback
// (GET /api/auth/google/callback)
func (_ Unimplemented) GoogleCallback(w http.ResponseWriter, r *http.Request, params GoogleCallbackParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Authenticate with email and password
// (POST /api/auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// End the current session
// (POST /api/auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current authenticated user
// (GET /api/auth/me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new user account
// (POST /api/auth/signup)
func (_ Unimplemented) Signup(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List calendar events with filters
// (GET /api/calendar-events)
func (_ Unimplemented) ListCalendarEvents(w http.ResponseWriter, r *http.Request, params ListCalendarEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Classify a calendar event (assign to project or skip)
// (PUT /api/calendar-events/{id}/classify)
func (_ Unimplemented) ClassifyCalendarEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List user's calendar connections
// (GET /api/calendars)
func (_ Unimplemented) ListCalendarConnections(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Disconnect a calendar
// (DELETE /api/calendars/{id})
func (_ Unimplemented) DeleteCalendarConnection(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List available calendars for a connection
// (GET /api/calendars/{id}/sources)
func (_ Unimplemented) ListCalendarSources(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update which calendars are selected for sync
// (PUT /api/calendars/{id}/sources)
func (_ Unimplemented) UpdateCalendarSources(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Trigger sync for a calendar connection
// (POST /api/calendars/{id}/sync)
func (_ Unimplemented) SyncCalendar(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all projects
// (GET /api/projects)
func (_ Unimplemented) ListProjects(w http.ResponseWriter, r *http.Request, params ListProjectsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new project
// (POST /api/projects)
func (_ Unimplemented) CreateProject(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a project
// (DELETE /api/projects/{id})
func (_ Unimplemented) DeleteProject(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a project by ID
// (GET /api/projects/{id})
func (_ Unimplemented) GetProject(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a project
// (PUT /api/projects/{id})
func (_ Unimplemented) UpdateProject(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List time entries
// (GET /api/time-entries)
func (_ Unimplemented) ListTimeEntries(w http.ResponseWriter, r *http.Request, params ListTimeEntriesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new time entry
// (POST /api/time-entries)
func (_ Unimplemented) CreateTimeEntry(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a time entry
// (DELETE /api/time-entries/{id})
func (_ Unimplemented) DeleteTimeEntry(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a time entry by ID
// (GET /api/time-entries/{id})
func (_ Unimplemented) GetTimeEntry(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a time entry
// (PUT /api/time-entries/{id})
func (_ Unimplemented) UpdateTimeEntry(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GoogleAuthorize operation middleware
func (siw *ServerInterfaceWrapper) GoogleAuthorize(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GoogleAuthorize(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GoogleCallback operation middleware
func (siw *ServerInterfaceWrapper) GoogleCallback(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GoogleCallbackParams

	// ------------- Required query parameter "code" -------------

	if paramValue := r.URL.Query().Get("code"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code", r.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := r.URL.Query().Get("state"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GoogleCallback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Signup operation middleware
func (siw *ServerInterfaceWrapper) Signup(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Signup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCalendarEvents operation middleware
func (siw *ServerInterfaceWrapper) ListCalendarEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCalendarEventsParams

	// ------------- Optional query parameter "start_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "start_date", r.URL.Query(), &params.StartDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start_date", Err: err})
		return
	}

	// ------------- Optional query parameter "end_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "end_date", r.URL.Query(), &params.EndDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end_date", Err: err})
		return
	}

	// ------------- Optional query parameter "classification_status" -------------

	err = runtime.BindQueryParameter("form", true, false, "classification_status", r.URL.Query(), &params.ClassificationStatus)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "classification_status", Err: err})
		return
	}

	// ------------- Optional query parameter "connection_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "connection_id", r.URL.Query(), &params.ConnectionId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "connection_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCalendarEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClassifyCalendarEvent operation middleware
func (siw *ServerInterfaceWrapper) ClassifyCalendarEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClassifyCalendarEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCalendarConnections operation middleware
func (siw *ServerInterfaceWrapper) ListCalendarConnections(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCalendarConnections(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCalendarConnection operation middleware
func (siw *ServerInterfaceWrapper) DeleteCalendarConnection(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCalendarConnection(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCalendarSources operation middleware
func (siw *ServerInterfaceWrapper) ListCalendarSources(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCalendarSources(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCalendarSources operation middleware
func (siw *ServerInterfaceWrapper) UpdateCalendarSources(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCalendarSources(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SyncCalendar operation middleware
func (siw *ServerInterfaceWrapper) SyncCalendar(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SyncCalendar(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjects operation middleware
func (siw *ServerInterfaceWrapper) ListProjects(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProjectsParams

	// ------------- Optional query parameter "include_archived" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_archived", r.URL.Query(), &params.IncludeArchived)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_archived", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjects(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProject operation middleware
func (siw *ServerInterfaceWrapper) DeleteProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProject(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProject(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProject operation middleware
func (siw *ServerInterfaceWrapper) UpdateProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProject(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTimeEntries operation middleware
func (siw *ServerInterfaceWrapper) ListTimeEntries(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTimeEntriesParams

	// ------------- Optional query parameter "start_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "start_date", r.URL.Query(), &params.StartDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start_date", Err: err})
		return
	}

	// ------------- Optional query parameter "end_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "end_date", r.URL.Query(), &params.EndDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end_date", Err: err})
		return
	}

	// ------------- Optional query parameter "project_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "project_id", r.URL.Query(), &params.ProjectId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTimeEntries(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTimeEntry operation middleware
func (siw *ServerInterfaceWrapper) CreateTimeEntry(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTimeEntry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTimeEntry operation middleware
func (siw *ServerInterfaceWrapper) DeleteTimeEntry(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTimeEntry(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTimeEntry operation middleware
func (siw *ServerInterfaceWrapper) GetTimeEntry(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTimeEntry(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTimeEntry operation middleware
func (siw *ServerInterfaceWrapper) UpdateTimeEntry(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTimeEntry(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/auth/google/authorize", wrapper.GoogleAuthorize)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/auth/google/callback", wrapper.GoogleCallback)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/auth/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/signup", wrapper.Signup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/calendar-events", wrapper.ListCalendarEvents)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/calendar-events/{id}/classify", wrapper.ClassifyCalendarEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/calendars", wrapper.ListCalendarConnections)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/calendars/{id}", wrapper.DeleteCalendarConnection)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/calendars/{id}/sources", wrapper.ListCalendarSources)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/calendars/{id}/sources", wrapper.UpdateCalendarSources)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/calendars/{id}/sync", wrapper.SyncCalendar)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/projects", wrapper.ListProjects)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/projects", wrapper.CreateProject)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/projects/{id}", wrapper.DeleteProject)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/projects/{id}", wrapper.GetProject)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/projects/{id}", wrapper.UpdateProject)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/time-entries", wrapper.ListTimeEntries)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/time-entries", wrapper.CreateTimeEntry)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/time-entries/{id}", wrapper.DeleteTimeEntry)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/time-entries/{id}", wrapper.GetTimeEntry)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/time-entries/{id}", wrapper.UpdateTimeEntry)
	})

	return r
}

type GoogleAuthorizeRequestObject struct {
}

type GoogleAuthorizeResponseObject interface {
	VisitGoogleAuthorizeResponse(w http.ResponseWriter) error
}

type GoogleAuthorize200JSONResponse OAuthAuthorizeResponse

func (response GoogleAuthorize200JSONResponse) VisitGoogleAuthorizeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GoogleAuthorize401JSONResponse Error

func (response GoogleAuthorize401JSONResponse) VisitGoogleAuthorizeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GoogleCallbackRequestObject struct {
	Params GoogleCallbackParams
}

type GoogleCallbackResponseObject interface {
	VisitGoogleCallbackResponse(w http.ResponseWriter) error
}

type GoogleCallback201JSONResponse CalendarConnection

func (response GoogleCallback201JSONResponse) VisitGoogleCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type GoogleCallback400JSONResponse Error

func (response GoogleCallback400JSONResponse) VisitGoogleCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GoogleCallback401JSONResponse Error

func (response GoogleCallback401JSONResponse) VisitGoogleCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Login400JSONResponse Error

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Login401JSONResponse Error

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout401JSONResponse Error

func (response Logout401JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUserRequestObject struct {
}

type GetCurrentUserResponseObject interface {
	VisitGetCurrentUserResponse(w http.ResponseWriter) error
}

type GetCurrentUser200JSONResponse User

func (response GetCurrentUser200JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUser401JSONResponse Error

func (response GetCurrentUser401JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SignupRequestObject struct {
	Body *SignupJSONRequestBody
}

type SignupResponseObject interface {
	VisitSignupResponse(w http.ResponseWriter) error
}

type Signup201JSONResponse AuthResponse

func (response Signup201JSONResponse) VisitSignupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type Signup400JSONResponse Error

func (response Signup400JSONResponse) VisitSignupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Signup409JSONResponse Error

func (response Signup409JSONResponse) VisitSignupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ListCalendarEventsRequestObject struct {
	Params ListCalendarEventsParams
}

type ListCalendarEventsResponseObject interface {
	VisitListCalendarEventsResponse(w http.ResponseWriter) error
}

type ListCalendarEvents200JSONResponse []CalendarEvent

func (response ListCalendarEvents200JSONResponse) VisitListCalendarEventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListCalendarEvents401JSONResponse Error

func (response ListCalendarEvents401JSONResponse) VisitListCalendarEventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ClassifyCalendarEventRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *ClassifyCalendarEventJSONRequestBody
}

type ClassifyCalendarEventResponseObject interface {
	VisitClassifyCalendarEventResponse(w http.ResponseWriter) error
}

type ClassifyCalendarEvent200JSONResponse ClassifyEventResponse

func (response ClassifyCalendarEvent200JSONResponse) VisitClassifyCalendarEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ClassifyCalendarEvent400JSONResponse Error

func (response ClassifyCalendarEvent400JSONResponse) VisitClassifyCalendarEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ClassifyCalendarEvent401JSONResponse Error

func (response ClassifyCalendarEvent401JSONResponse) VisitClassifyCalendarEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ClassifyCalendarEvent404JSONResponse Error

func (response ClassifyCalendarEvent404JSONResponse) VisitClassifyCalendarEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListCalendarConnectionsRequestObject struct {
}

type ListCalendarConnectionsResponseObject interface {
	VisitListCalendarConnectionsResponse(w http.ResponseWriter) error
}

type ListCalendarConnections200JSONResponse []CalendarConnection

func (response ListCalendarConnections200JSONResponse) VisitListCalendarConnectionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListCalendarConnections401JSONResponse Error

func (response ListCalendarConnections401JSONResponse) VisitListCalendarConnectionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCalendarConnectionRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteCalendarConnectionResponseObject interface {
	VisitDeleteCalendarConnectionResponse(w http.ResponseWriter) error
}

type DeleteCalendarConnection204Response struct {
}

func (response DeleteCalendarConnection204Response) VisitDeleteCalendarConnectionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteCalendarConnection401JSONResponse Error

func (response DeleteCalendarConnection401JSONResponse) VisitDeleteCalendarConnectionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCalendarConnection404JSONResponse Error

func (response DeleteCalendarConnection404JSONResponse) VisitDeleteCalendarConnectionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListCalendarSourcesRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type ListCalendarSourcesResponseObject interface {
	VisitListCalendarSourcesResponse(w http.ResponseWriter) error
}

type ListCalendarSources200JSONResponse []Calendar

func (response ListCalendarSources200JSONResponse) VisitListCalendarSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListCalendarSources401JSONResponse Error

func (response ListCalendarSources401JSONResponse) VisitListCalendarSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListCalendarSources404JSONResponse Error

func (response ListCalendarSources404JSONResponse) VisitListCalendarSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateCalendarSourcesRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateCalendarSourcesJSONRequestBody
}

type UpdateCalendarSourcesResponseObject interface {
	VisitUpdateCalendarSourcesResponse(w http.ResponseWriter) error
}

type UpdateCalendarSources200JSONResponse []Calendar

func (response UpdateCalendarSources200JSONResponse) VisitUpdateCalendarSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateCalendarSources401JSONResponse Error

func (response UpdateCalendarSources401JSONResponse) VisitUpdateCalendarSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateCalendarSources404JSONResponse Error

func (response UpdateCalendarSources404JSONResponse) VisitUpdateCalendarSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SyncCalendarRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type SyncCalendarResponseObject interface {
	VisitSyncCalendarResponse(w http.ResponseWriter) error
}

type SyncCalendar200JSONResponse SyncResult

func (response SyncCalendar200JSONResponse) VisitSyncCalendarResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SyncCalendar401JSONResponse Error

func (response SyncCalendar401JSONResponse) VisitSyncCalendarResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SyncCalendar404JSONResponse Error

func (response SyncCalendar404JSONResponse) VisitSyncCalendarResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListProjectsRequestObject struct {
	Params ListProjectsParams
}

type ListProjectsResponseObject interface {
	VisitListProjectsResponse(w http.ResponseWriter) error
}

type ListProjects200JSONResponse []Project

func (response ListProjects200JSONResponse) VisitListProjectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListProjects401JSONResponse Error

func (response ListProjects401JSONResponse) VisitListProjectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateProjectRequestObject struct {
	Body *CreateProjectJSONRequestBody
}

type CreateProjectResponseObject interface {
	VisitCreateProjectResponse(w http.ResponseWriter) error
}

type CreateProject201JSONResponse Project

func (response CreateProject201JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateProject400JSONResponse Error

func (response CreateProject400JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateProject401JSONResponse Error

func (response CreateProject401JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProjectRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteProjectResponseObject interface {
	VisitDeleteProjectResponse(w http.ResponseWriter) error
}

type DeleteProject204Response struct {
}

func (response DeleteProject204Response) VisitDeleteProjectResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteProject401JSONResponse Error

func (response DeleteProject401JSONResponse) VisitDeleteProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProject404JSONResponse Error

func (response DeleteProject404JSONResponse) VisitDeleteProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProject409JSONResponse Error

func (response DeleteProject409JSONResponse) VisitDeleteProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetProjectRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetProjectResponseObject interface {
	VisitGetProjectResponse(w http.ResponseWriter) error
}

type GetProject200JSONResponse Project

func (response GetProject200JSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProject401JSONResponse Error

func (response GetProject401JSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetProject404JSONResponse Error

func (response GetProject404JSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProjectRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateProjectJSONRequestBody
}

type UpdateProjectResponseObject interface {
	VisitUpdateProjectResponse(w http.ResponseWriter) error
}

type UpdateProject200JSONResponse Project

func (response UpdateProject200JSONResponse) VisitUpdateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProject400JSONResponse Error

func (response UpdateProject400JSONResponse) VisitUpdateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProject401JSONResponse Error

func (response UpdateProject401JSONResponse) VisitUpdateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProject404JSONResponse Error

func (response UpdateProject404JSONResponse) VisitUpdateProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListTimeEntriesRequestObject struct {
	Params ListTimeEntriesParams
}

type ListTimeEntriesResponseObject interface {
	VisitListTimeEntriesResponse(w http.ResponseWriter) error
}

type ListTimeEntries200JSONResponse []TimeEntry

func (response ListTimeEntries200JSONResponse) VisitListTimeEntriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListTimeEntries401JSONResponse Error

func (response ListTimeEntries401JSONResponse) VisitListTimeEntriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateTimeEntryRequestObject struct {
	Body *CreateTimeEntryJSONRequestBody
}

type CreateTimeEntryResponseObject interface {
	VisitCreateTimeEntryResponse(w http.ResponseWriter) error
}

type CreateTimeEntry201JSONResponse TimeEntry

func (response CreateTimeEntry201JSONResponse) VisitCreateTimeEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTimeEntry400JSONResponse Error

func (response CreateTimeEntry400JSONResponse) VisitCreateTimeEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTimeEntry401JSONResponse Error

func (response CreateTimeEntry401JSONResponse) VisitCreateTimeEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateTimeEntry404JSONResponse Error

func (response CreateTimeEntry404JSONResponse) VisitCreateTimeEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTimeEntryRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteTimeEntryResponseObject interface {
	VisitDeleteTimeEntryResponse(w http.ResponseWriter) error
}

type DeleteTimeEntry204Response struct {
}

func (response DeleteTimeEntry204Response) VisitDeleteTimeEntryResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTimeEntry401JSONResponse Error

func (response DeleteTimeEntry401JSONResponse) VisitDeleteTimeEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTimeEntry404JSONResponse Error

func (response DeleteTimeEntry404JSONResponse) VisitDeleteTimeEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTimeEntry409JSONResponse Error

func (response DeleteTimeEntry409JSONResponse) VisitDeleteTimeEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetTimeEntryRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetTimeEntryResponseObject interface {
	VisitGetTimeEntryResponse(w http.ResponseWriter) error
}

type GetTimeEntry200JSONResponse TimeEntry

func (response GetTimeEntry200JSONResponse) VisitGetTimeEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTimeEntry401JSONResponse Error

func (response GetTimeEntry401JSONResponse) VisitGetTimeEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetTimeEntry404JSONResponse Error

func (response GetTimeEntry404JSONResponse) VisitGetTimeEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTimeEntryRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateTimeEntryJSONRequestBody
}

type UpdateTimeEntryResponseObject interface {
	VisitUpdateTimeEntryResponse(w http.ResponseWriter) error
}

type UpdateTimeEntry200JSONResponse TimeEntry

func (response UpdateTimeEntry200JSONResponse) VisitUpdateTimeEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTimeEntry400JSONResponse Error

func (response UpdateTimeEntry400JSONResponse) VisitUpdateTimeEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTimeEntry401JSONResponse Error

func (response UpdateTimeEntry401JSONResponse) VisitUpdateTimeEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTimeEntry404JSONResponse Error

func (response UpdateTimeEntry404JSONResponse) VisitUpdateTimeEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTimeEntry409JSONResponse Error

func (response UpdateTimeEntry409JSONResponse) VisitUpdateTimeEntryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get Google OAuth authorization URL
	// (GET /api/auth/google/authorize)
	GoogleAuthorize(ctx context.Context, request GoogleAuthorizeRequestObject) (GoogleAuthorizeResponseObject, error)
	// Handle Google OAuth callback
	// (GET /api/auth/google/callback)
	GoogleCallback(ctx context.Context, request GoogleCallbackRequestObject) (GoogleCallbackResponseObject, error)
	// Authenticate with email and password
	// (POST /api/auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// End the current session
	// (POST /api/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Get current authenticated user
	// (GET /api/auth/me)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)
	// Create a new user account
	// (POST /api/auth/signup)
	Signup(ctx context.Context, request SignupRequestObject) (SignupResponseObject, error)
	// List calendar events with filters
	// (GET /api/calendar-events)
	ListCalendarEvents(ctx context.Context, request ListCalendarEventsRequestObject) (ListCalendarEventsResponseObject, error)
	// Classify a calendar event (assign to project or skip)
	// (PUT /api/calendar-events/{id}/classify)
	ClassifyCalendarEvent(ctx context.Context, request ClassifyCalendarEventRequestObject) (ClassifyCalendarEventResponseObject, error)
	// List user's calendar connections
	// (GET /api/calendars)
	ListCalendarConnections(ctx context.Context, request ListCalendarConnectionsRequestObject) (ListCalendarConnectionsResponseObject, error)
	// Disconnect a calendar
	// (DELETE /api/calendars/{id})
	DeleteCalendarConnection(ctx context.Context, request DeleteCalendarConnectionRequestObject) (DeleteCalendarConnectionResponseObject, error)
	// List available calendars for a connection
	// (GET /api/calendars/{id}/sources)
	ListCalendarSources(ctx context.Context, request ListCalendarSourcesRequestObject) (ListCalendarSourcesResponseObject, error)
	// Update which calendars are selected for sync
	// (PUT /api/calendars/{id}/sources)
	UpdateCalendarSources(ctx context.Context, request UpdateCalendarSourcesRequestObject) (UpdateCalendarSourcesResponseObject, error)
	// Trigger sync for a calendar connection
	// (POST /api/calendars/{id}/sync)
	SyncCalendar(ctx context.Context, request SyncCalendarRequestObject) (SyncCalendarResponseObject, error)
	// List all projects
	// (GET /api/projects)
	ListProjects(ctx context.Context, request ListProjectsRequestObject) (ListProjectsResponseObject, error)
	// Create a new project
	// (POST /api/projects)
	CreateProject(ctx context.Context, request CreateProjectRequestObject) (CreateProjectResponseObject, error)
	// Delete a project
	// (DELETE /api/projects/{id})
	DeleteProject(ctx context.Context, request DeleteProjectRequestObject) (DeleteProjectResponseObject, error)
	// Get a project by ID
	// (GET /api/projects/{id})
	GetProject(ctx context.Context, request GetProjectRequestObject) (GetProjectResponseObject, error)
	// Update a project
	// (PUT /api/projects/{id})
	UpdateProject(ctx context.Context, request UpdateProjectRequestObject) (UpdateProjectResponseObject, error)
	// List time entries
	// (GET /api/time-entries)
	ListTimeEntries(ctx context.Context, request ListTimeEntriesRequestObject) (ListTimeEntriesResponseObject, error)
	// Create a new time entry
	// (POST /api/time-entries)
	CreateTimeEntry(ctx context.Context, request CreateTimeEntryRequestObject) (CreateTimeEntryResponseObject, error)
	// Delete a time entry
	// (DELETE /api/time-entries/{id})
	DeleteTimeEntry(ctx context.Context, request DeleteTimeEntryRequestObject) (DeleteTimeEntryResponseObject, error)
	// Get a time entry by ID
	// (GET /api/time-entries/{id})
	GetTimeEntry(ctx context.Context, request GetTimeEntryRequestObject) (GetTimeEntryResponseObject, error)
	// Update a time entry
	// (PUT /api/time-entries/{id})
	UpdateTimeEntry(ctx context.Context, request UpdateTimeEntryRequestObject) (UpdateTimeEntryResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GoogleAuthorize operation middleware
func (sh *strictHandler) GoogleAuthorize(w http.ResponseWriter, r *http.Request) {
	var request GoogleAuthorizeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GoogleAuthorize(ctx, request.(GoogleAuthorizeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GoogleAuthorize")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GoogleAuthorizeResponseObject); ok {
		if err := validResponse.VisitGoogleAuthorizeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GoogleCallback operation middleware
func (sh *strictHandler) GoogleCallback(w http.ResponseWriter, r *http.Request, params GoogleCallbackParams) {
	var request GoogleCallbackRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GoogleCallback(ctx, request.(GoogleCallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GoogleCallback")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GoogleCallbackResponseObject); ok {
		if err := validResponse.VisitGoogleCallbackResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCurrentUser operation middleware
func (sh *strictHandler) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	var request GetCurrentUserRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUser(ctx, request.(GetCurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCurrentUserResponseObject); ok {
		if err := validResponse.VisitGetCurrentUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Signup operation middleware
func (sh *strictHandler) Signup(w http.ResponseWriter, r *http.Request) {
	var request SignupRequestObject

	var body SignupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Signup(ctx, request.(SignupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Signup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SignupResponseObject); ok {
		if err := validResponse.VisitSignupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCalendarEvents operation middleware
func (sh *strictHandler) ListCalendarEvents(w http.ResponseWriter, r *http.Request, params ListCalendarEventsParams) {
	var request ListCalendarEventsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCalendarEvents(ctx, request.(ListCalendarEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCalendarEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCalendarEventsResponseObject); ok {
		if err := validResponse.VisitListCalendarEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ClassifyCalendarEvent operation middleware
func (sh *strictHandler) ClassifyCalendarEvent(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request ClassifyCalendarEventRequestObject

	request.Id = id

	var body ClassifyCalendarEventJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ClassifyCalendarEvent(ctx, request.(ClassifyCalendarEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ClassifyCalendarEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ClassifyCalendarEventResponseObject); ok {
		if err := validResponse.VisitClassifyCalendarEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCalendarConnections operation middleware
func (sh *strictHandler) ListCalendarConnections(w http.ResponseWriter, r *http.Request) {
	var request ListCalendarConnectionsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCalendarConnections(ctx, request.(ListCalendarConnectionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCalendarConnections")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCalendarConnectionsResponseObject); ok {
		if err := validResponse.VisitListCalendarConnectionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCalendarConnection operation middleware
func (sh *strictHandler) DeleteCalendarConnection(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteCalendarConnectionRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCalendarConnection(ctx, request.(DeleteCalendarConnectionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCalendarConnection")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteCalendarConnectionResponseObject); ok {
		if err := validResponse.VisitDeleteCalendarConnectionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCalendarSources operation middleware
func (sh *strictHandler) ListCalendarSources(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request ListCalendarSourcesRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCalendarSources(ctx, request.(ListCalendarSourcesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCalendarSources")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCalendarSourcesResponseObject); ok {
		if err := validResponse.VisitListCalendarSourcesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateCalendarSources operation middleware
func (sh *strictHandler) UpdateCalendarSources(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateCalendarSourcesRequestObject

	request.Id = id

	var body UpdateCalendarSourcesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateCalendarSources(ctx, request.(UpdateCalendarSourcesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateCalendarSources")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateCalendarSourcesResponseObject); ok {
		if err := validResponse.VisitUpdateCalendarSourcesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SyncCalendar operation middleware
func (sh *strictHandler) SyncCalendar(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request SyncCalendarRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SyncCalendar(ctx, request.(SyncCalendarRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SyncCalendar")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SyncCalendarResponseObject); ok {
		if err := validResponse.VisitSyncCalendarResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProjects operation middleware
func (sh *strictHandler) ListProjects(w http.ResponseWriter, r *http.Request, params ListProjectsParams) {
	var request ListProjectsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListProjects(ctx, request.(ListProjectsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProjects")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListProjectsResponseObject); ok {
		if err := validResponse.VisitListProjectsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProject operation middleware
func (sh *strictHandler) CreateProject(w http.ResponseWriter, r *http.Request) {
	var request CreateProjectRequestObject

	var body CreateProjectJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProject(ctx, request.(CreateProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateProjectResponseObject); ok {
		if err := validResponse.VisitCreateProjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteProject operation middleware
func (sh *strictHandler) DeleteProject(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteProjectRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteProject(ctx, request.(DeleteProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteProject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteProjectResponseObject); ok {
		if err := validResponse.VisitDeleteProjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProject operation middleware
func (sh *strictHandler) GetProject(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetProjectRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProject(ctx, request.(GetProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProjectResponseObject); ok {
		if err := validResponse.VisitGetProjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateProject operation middleware
func (sh *strictHandler) UpdateProject(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateProjectRequestObject

	request.Id = id

	var body UpdateProjectJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateProject(ctx, request.(UpdateProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateProject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateProjectResponseObject); ok {
		if err := validResponse.VisitUpdateProjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTimeEntries operation middleware
func (sh *strictHandler) ListTimeEntries(w http.ResponseWriter, r *http.Request, params ListTimeEntriesParams) {
	var request ListTimeEntriesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTimeEntries(ctx, request.(ListTimeEntriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTimeEntries")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTimeEntriesResponseObject); ok {
		if err := validResponse.VisitListTimeEntriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTimeEntry operation middleware
func (sh *strictHandler) CreateTimeEntry(w http.ResponseWriter, r *http.Request) {
	var request CreateTimeEntryRequestObject

	var body CreateTimeEntryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTimeEntry(ctx, request.(CreateTimeEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTimeEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTimeEntryResponseObject); ok {
		if err := validResponse.VisitCreateTimeEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteTimeEntry operation middleware
func (sh *strictHandler) DeleteTimeEntry(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteTimeEntryRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTimeEntry(ctx, request.(DeleteTimeEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTimeEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteTimeEntryResponseObject); ok {
		if err := validResponse.VisitDeleteTimeEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTimeEntry operation middleware
func (sh *strictHandler) GetTimeEntry(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetTimeEntryRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTimeEntry(ctx, request.(GetTimeEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTimeEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTimeEntryResponseObject); ok {
		if err := validResponse.VisitGetTimeEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTimeEntry operation middleware
func (sh *strictHandler) UpdateTimeEntry(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateTimeEntryRequestObject

	request.Id = id

	var body UpdateTimeEntryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTimeEntry(ctx, request.(UpdateTimeEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTimeEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateTimeEntryResponseObject); ok {
		if err := validResponse.VisitUpdateTimeEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
